dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      - libnss3

language: node_js
sudo: false

node_js:
  - '6'
  - '8'
  - '9'
  - '10'
  - '11'

before_install:
  # Info about OS
  - uname -a
  - if [[ `node -v` = v6* ]]; then npm i -g npx; fi
  - npx --version
  # Enable user namespace cloning
  - if [[ "`uname`" == "Linux" ]]; then 'sysctl kernel.unprivileged_userns_clone=1'; fi
  # Launch XVFB
  - if [[ "`uname`" == "Linux" ]]; then 'export DISPLAY=:99.0'; fi
  - if [[ "`uname`" == "Linux" ]]; then 'sh -e /etc/init.d/xvfb start'; fi

script:
  - node --version
  - npm --version
  - npx --version
  - npm test

os:
  - linux
  - osx
