dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      - libnss3

language: node_js
sudo: false

node_js:
  - '6'
  - '8'
  - '9'
  - '10'
  - '11'

before_install:
  - if [[ `node -v` = v6* ]]; then npm i -g npx; fi
  - npx --version
  # Enable user namespace cloning
  - 'sysctl kernel.unprivileged_userns_clone=1'
  # Launch XVFB
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

script:
  - node --version
  - npm --version
  - npx --version
  - npm test

os:
  - linux
  - osx
