addons:
  chrome: stable
  apt:
    packages:
      - libnss3

language: node_js
sudo: false

node_js:
  - '6'
  - '8'
  - '9'
  - '10'
  - '11'

before_install:
  # Info about OS
  - uname
  - if [[ `node -v` = v6* ]]; then npm i -g npx; fi
  - npx --version
  # Launch XVFB
  - if [[ `uname` = "Linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ `uname` = "Linux" ]]; then sh -e /etc/init.d/xvfb start; fi

script:
  - node --version
  - npm --version
  - npx --version
  - npm run test-with-no-coverage

os:
  - linux
  - osx
